# Generated by Django 5.1.2 on 2024-11-02 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='report',
            table='report',
        ),
    ]
