# Generated by Django 5.1.2 on 2024-11-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_report_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='customer_id',
            field=models.CharField(max_length=255),
        ),
    ]
