name: Build and Publish Docker Image

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  
        password: ${{ secrets.DOCKER_PASSWORD }} 

    - name: Build and Push Docker Image
      run: |
          docker build -t talalbadreddine/sales_etl:${{ github.sha }} .
          docker push talalbadreddine/sales_etl:${{ github.sha }}
