name: Pull and Run Docker Image on EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Start SSH Agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Pull Docker Image and Run on EC2
      shell: bash
      run: |
        if [ -f ~/.ssh/ec2_key ]; then
          echo "SSH key exists."
          ls -l ~/.ssh/ec2_key
        else
          echo "SSH key does not exist."
          exit 1
        fi
        ssh -v -i ~/.ssh/ec2_key -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Ensure correct permissions for SSH directories and files
          sudo chmod 700 /root/.ssh
          sudo chmod 600 /root/.ssh/authorized_keys

          # Update package list
          sudo apt-get update

          # Check for Docker installation, and install if not found
          if ! command -v docker &> /dev/null; then
              sudo apt-get install -y docker.io
          fi

          # Stop and remove existing container if it exists
          if [ "$(docker ps -q -f name=sales_etl_container)" ]; then
              docker stop sales_etl_container
              docker rm sales_etl_container
          fi

          # Pull the Docker image from Docker Hub using the commit SHA as the tag
          docker pull talalbadreddine/sales_etl:${{ github.sha }}

          # Run the Docker container
          docker run -d --name sales_etl_container talalbadreddine/sales_etl:${{ github.sha }}
        EOF